#pragma once

#include <QApplication>
#include <QMainWindow>
#include <QTextEdit>
#include <QPlainTextEdit>
#include <QSyntaxHighlighter>
#include <QTextCharFormat>
#include <QRegularExpression>
#include <QTimer>
#include <QPushButton>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFileDialog>
#include <QMessageBox>
#include <QTextStream>
#include <QStatusBar>
#include <QMenuBar>
#include <QMenu>
#include <QAction>
#include <QKeySequence>
#include <QFile>
#include <QTextCodec>
#include <QCompleter>
#include <QStackedWidget>
#include <QTabWidget>
#include <QDockWidget>
#include <QTreeView>
#include <QFileSystemModel>
#include <QLabel>
#include <QListWidget>
#include <QListWidgetItem>
#include <QGraphicsDropShadowEffect>
#include <QPropertyAnimation>
#include <QPainter>
#include <QTextBlock>
#include <QTextCursor>
#include <QTextDocumentFragment>
#include <QTextDocument>
#include <QScrollBar>
#include <QInputDialog>
#include <QColorDialog>
#include <QCheckBox>
#include <QLineEdit>
#include <QDialog>
#include <QGridLayout>
#include <QDialogButtonBox>
#include <QProcess>
#include <QSettings>
#include <QElapsedTimer>
#include <QTextCodec>
#include <QByteArray>
#include <QDebug>
#include <QFontMetrics>
#include <QFontDialog>
#include <QStackedWidget>
#include <QTimer>
#include <QPropertyAnimation>
#include <QGraphicsEffect>
#include <QTextCodec>
#include <QByteArray>
#include <QTextDecoder>
#include <QTextEncoder>
