#ifndef INCLUDES_H
#define INCLUDES_H

#include <QApplication>
#include <QMainWindow>
#include <QPlainTextEdit>
#include <QSyntaxHighlighter>
#include <QRegularExpression>
#include <QFile>
#include <QMenuBar>
#include <QToolBar>
#include <QStatusBar>
#include <QLabel>
#include <QDockWidget>
#include <QFontDatabase>
#include <QShortcut>
#include <QMessageBox>
#include <QFileDialog>
#include <QSettings>
#include <QCompleter>
#include <QStringListModel>
#include <QTextStream>
#include <QFileInfo>
#include <QIcon>
#include <QPalette>
#include <QTextCursor>
#include <QTextBlock>
#include <QTextDocument>
#include <QStyleFactory>
#include <QFontMetrics>
#include <QFileSystemModel>
#include <QTreeView>
#include <QProcess>
#include <QDir>
#include <QDesktopServices>
#include <QUrl>
#include <QTextCharFormat>
#include <QAbstractItemView>
#include <QInputDialog>
#include <QHeaderView>
#include <QPushButton>
#include <QVBoxLayout>
#include <QListWidget>
#include <QStackedWidget>
#include <QPainter>
#include <QScrollBar>
#include <QStringConverter>
#include <QCheckBox>
#include <QRadioButton>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QSplitter>
#include <QTabWidget>
#include <QTextCodec>
#include <QPropertyAnimation>
#include <QParallelAnimationGroup>
#include <QFileSystemModel>

#endif
