#pragma once

#include <QApplication>
#include <QMainWindow>
#include <QPlainTextEdit>
#include <QSyntaxHighlighter>
#include <QRegularExpression>
#include <QTextDocument>
#include <QTextCursor>
#include <QTextBlock>
#include <QTextCharFormat>
#include <QFont>
#include <QFontMetrics>
#include <QPalette>
#include <QColor>
#include <QPainter>
#include <QFile>
#include <QFileInfo>
#include <QFileDialog>
#include <QMessageBox>
#include <QInputDialog>
#include <QDialog>
#include <QDialogButtonBox>
#include <QCheckBox>
#include <QLineEdit>
#include <QLabel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QMenu>
#include <QMenuBar>
#include <QToolBar>
#include <QStatusBar>
#include <QAction>
#include <QKeySequence>
#include <QSettings>
#include <QProcess>
#include <QTimer>
#include <QStackedWidget>
#include <QTabWidget>
#include <QListWidget>
#include <QTreeView>
#include <QFileSystemModel>
#include <QDockWidget>
#include <QDesktopServices>
#include <QUrl>
#include <QIcon>
#include <QTextStream>
#include <QTextCodec>
#include <QCompleter>
#include <QStringListModel>
#include <QAbstractItemView>
#include <QScrollArea>
#include <QSplitter>
#include <QTextBrowser>
#include <QDateTime>
#include <QColorDialog>
#include <QFontDialog>
#include <QElapsedTimer>
#include <QGraphicsDropShadowEffect>
#include <QGraphicsOpacityEffect>
#include <QPropertyAnimation>
#include <QSequentialAnimationGroup>
#include <QEasingCurve>
#include <QDir>
